targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          generate_for:
            - lib/**
      auto_route_generator:auto_route_generator:
        options:
          replace_in_route_name: "Screen,Route"